### PR TITLE
Fix bug in DimmerItem that tries to getItemState before connection established

### PR DESCRIPTION
**Pull request by Nexus2k**
Plus update to latest node-lox-ws-api and switch to Token-Enc Auth.

### CODE REVIEW

**Comment by WolfMa99** [comment]
Still with the changes it throws the same error. Any ideas?

**Comment by Nexus2k** [comment]
Can you post the full error message?

**Comment by WolfMa99** [comment]
`[2018-02-08 10:58:31] [Loxone] [dimmer] iOS - send brightness message to Master-Helligkeit of Lichtsteuerung in Kinderzimmer: 0
/opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190
    this.connection.send(this._auth.prepare_control_command(control, command));
                                   ^

TypeError: Cannot read property 'prepare_control_command' of undefined
    at API.send_control_command (/opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190:36)
    at API.send_cmd (/opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:203:10)
    at WSListener.sendCommand (/opt/node/lib/node_modules/homebridge-loxone-ws/libs/WSListener.js:113:13)
    at DimmerItem.setItemState (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:95:22)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:311:10)
    at DimmerItem.getOtherServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:54:10)
    at DimmerItem.AbstractItem.getServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/AbstractItem.js:30:30)
    at Server._createAccessory (/opt/node/lib/node_modules/homebridge/lib/server.js:388:36)`

**Comment by Nexus2k** [comment]
I've added the same fix to the setItemState function, you might want to pull the latest version and try again.

**Comment by WolfMa99** [comment]
Now it throws:

[2018-02-08 11:29:05] [Loxone] [dimmer] iOS - send brightness message to Master-Helligkeit of Lichtsteuerung in Kinderzimmer: 0
/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:95
    if (this.platform.ws.is_connected()) {
                         ^

TypeError: this.platform.ws.is_connected is not a function
    at DimmerItem.setItemState (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:95:26)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:311:10)
    at DimmerItem.getOtherServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:54:10)
    at DimmerItem.AbstractItem.getServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/AbstractItem.js:30:30)
    at Server._createAccessory (/opt/node/lib/node_modules/homebridge/lib/server.js:388:36)
    at Server.<anonymous> (/opt/node/lib/node_modules/homebridge/lib/server.js:374:32)
    at /opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Request._callback (/opt/node/lib/node_modules/homebridge-loxone-ws/index.js:67:13)

**Comment by Nexus2k** [comment]
Hmmm... Very strange, sounds like the WebSocket is not connected at this point. I added another check for that. I do however currently expect that the login credentials are wrong.

**Comment by WolfMa99** [comment]
it throws again the same error, but I think the credentials are right because it connects and see everything

**Comment by WolfMa99** [comment]
I could solve the problem by setting if (this.connection !== undefined) {
      this.platform.ws.sendCommand(this.uuidAction, command);
    }
I can control now from Home in iOS the color and brightness, but always show the old state, after I click on it, it changes to the new one. I hope you can help me with that.

**Comment by Nexus2k** [comment]
this.connection will always be undefined as it doesn't exist, the idea is to check if the this.platform.ws object is already assigned which indicates that it's connected.

**Comment by WolfMa99** [comment]
How to achieve that? Because for now I can control over HomeKit the color and so.

**Comment by Nexus2k** [comment]
```
if (this.platform.ws !== undefined) {
  this.platform.ws.sendCommand(this.uuidAction, command);
}
```
might work

**Comment by WolfMa99** [comment]
This throws the error from the beginning: /opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190
    this.connection.send(this._auth.prepare_control_command(control, command));
                                   ^

TypeError: Cannot read property 'prepare_control_command' of undefined
    at API.send_control_command (/opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190:36)
    at API.send_cmd (/opt/node/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:203:10)
    at WSListener.sendCommand (/opt/node/lib/node_modules/homebridge-loxone-ws/libs/WSListener.js:113:13)
    at DimmerItem.setItemState (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:96:24)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:311:10)
    at DimmerItem.getOtherServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/DimmerItem.js:54:10)
    at DimmerItem.AbstractItem.getServices (/opt/node/lib/node_modules/homebridge-loxone-ws/items/AbstractItem.js:30:30)
    at Server._createAccessory (/opt/node/lib/node_modules/homebridge/lib/server.js:388:36)

**Comment by WolfMa99** [comment]
Hey,
Do you have now Andy idea? How to fix the problem? Shall i try a new and Fresh Installation?

**Comment by vsolov** [comment]
guys, try this solution.. 
edit file DimmerItem.js
  
4:   var runonce = 0;
92:  if (runonce ==0) {
93:  runonce = 1;
94:  callback();
95: return;
96: }


now it work :D  dimmer correctly initialize

**Pull request merged**
