### PR TITLE
New Controls...

### LINKED ISSUE #10: Lots of accessories missing
I've just tested Homebridge with your Loxone plugin and it is pretty nice.

But in the Home app, I'm missing lots of accessories. In my case, there is only one Blinds/Jalousie item and there are also not all light items available.

The console output of Homebridge also does not list the missing items, so I think that's an issue with the plugin.

### LINKED ISSUE #16: Not working with release of Loxone 9.0.9.26
homebridge-loxone-ws doesn't work anymore since update 9.0.9.26. I noticed that one way status update from Loxone to HomeKit worked but after some reboots of the homebridge pi this functionality is also broken.

### PR DESCRIPTION
**Pull request by idoodler**
- Added support for LightControllerV2s ColorPickerV2
- Controls with the same name are supported now (itemLists keys are now the controls UUIDs) -> Fixes #10
- Controls are now easier to identify by appending the room to the control and the parent controls name to the subcontrol
- Modernized and unified code
- Incremented package.json version
- Updated to the new node-lox-ws-api -> Fixes #16 and #17 

Everything has been tested by me in my home.

### CODE REVIEW

**Comment by DerFlash** [comment]
You only support multiple items with the same name within the ItemFactorys itemList, and I assume it then just works for you, because in fact you don't really have "same item names" after you also appended the room name to the item name now*
If they really would have the same name in the same room, your code would still fail.
See my additions in AbstractItem.js in my pull request https://github.com/Sroose/homebridge-loxone-ws/pull/12 for fixing this.

* personally, I don't really like doing this. It's not the original name and will result in bad HomeKit behaviour like now the HomeKit app no longer can "guess" the rooms main light (based on the fact that it has the exact name of its room)

Still, this is another good heads up here. Would be nice if @Sroose would pick up the good work again.

Kind regards
Björn

**Comment by idoodler** [comment]
@DerFlash Thats right. My main intention in appending the room to the controls name was to better identify the control in the initial setup process, you can easily change it in this process. It would be great, if @Sroose also accepts #12.

**Comment by DerFlash** [comment]
@idoodler Good point about changing the name back in the adding process later. I'll revert my opinion. You're right, it may help in bigger setups.

**Comment by tomasbarej** [comment]
Tested yesterday and works good in my Loxone 9 setup. There was just one problem with an loxone function block that was not assigned to any room and forbid me to initiate the homebridge plugin.

Condition to check that _controlRoom_ variable isn't an _undefined_ needs to be added in ItemFactory.js
`controlRoom = factory.roomList[control.room];`

**Comment by idoodler** [comment]
@tomasbarej I just added a check for the _undefined_ room property.

**Comment by Djhaico** [comment]
Hey Guys,

Nice project, great work!

Im new at this form,and i installed homekit for my Loxone project. I can read with my ipad what light is on or off, but when i give a command to swhitch the light on, the light doesn't go on. Command is sent to loxone, but Loxone doesn't response.

Is this a bug, or im not on the right sofware version ?
Homebridge API Version 2.2

Can someone help me with this problem?

Kind regards,

Haico

**Pull request merged**
